In [ ]:
import yfinance as yf
import pandas as pd
import numpy as np

In [3]:
ticker = "AAPL"
df = yf.download(ticker, start="2021-01-01", end="2026-03-12")

[*********************100%***********************]  1 of 1 completed

In [4]:
df.head()

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2021-01-04  125.856720  129.941395  123.279481  129.853870  143301900
2021-01-05  127.412758  128.122724  124.903597  125.350973   97664900
2021-01-06  123.123856  127.451673  122.909895  124.213106  155088000
2021-01-07  127.325211  128.015722  124.349234  124.835505  109578200
2021-01-08  128.424210  128.988286  126.654176  128.793766  105158200

In [5]:
df.columns

MultiIndex([( 'Close', 'AAPL'),
            (  'High', 'AAPL'),
            (   'Low', 'AAPL'),
            (  'Open', 'AAPL'),
            ('Volume', 'AAPL')],
           names=['Price', 'Ticker'])

In [6]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1302 entries, 2021-01-04 to 2026-03-11
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   1302 non-null   float64
 1   (High, AAPL)    1302 non-null   float64
 2   (Low, AAPL)     1302 non-null   float64
 3   (Open, AAPL)    1302 non-null   float64
 4   (Volume, AAPL)  1302 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 61.0 KB

In [7]:
df['Returns'] = df['Close'].pct_change()

In [8]:
df['Rolling_Vol'] = df['Returns'].rolling(window=21).std() * np.sqrt(252)

In [9]:
df['Target_Vol'] = df['Rolling_Vol'].shift(-5)

In [10]:
df.dropna(inplace=True)

In [11]:
df.head()

Price,Close,High,Low,Open,Volume,Returns,Rolling_Vol,Target_Vol
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,,,
Date,,,,,,,,
2021-02-03,130.262314,132.042068,129.941373,132.032333,89880900,-0.007778,0.358685,0.313887
2021-02-04,133.617584,133.627304,130.894463,132.557517,84183100,0.025758,0.366532,0.313975
2021-02-05,133.203629,133.846469,132.327038,133.778297,75693800,-0.003098,0.343056,0.310007
2021-02-08,133.349716,133.398419,131.411460,132.492595,71297200,0.001097,0.325094,0.310699
2021-02-09,132.473145,134.294527,132.317317,133.067282,76774200,-0.006573,0.325690,0.313449